/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package absli.uid.helper.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Absli service. Represents a row in the &quot;AB_Absli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>absli.uid.helper.model.impl.AbsliModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>absli.uid.helper.model.impl.AbsliImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Absli
 * @generated
 */
@ProviderType
public interface AbsliModel
	extends BaseModel<Absli>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a absli model instance should use the {@link Absli} interface instead.
	 */

	/**
	 * Returns the primary key of this absli.
	 *
	 * @return the primary key of this absli
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this absli.
	 *
	 * @param primaryKey the primary key of this absli
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this absli.
	 *
	 * @return the uuid of this absli
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this absli.
	 *
	 * @param uuid the uuid of this absli
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this absli.
	 *
	 * @return the ID of this absli
	 */
	public long getId();

	/**
	 * Sets the ID of this absli.
	 *
	 * @param id the ID of this absli
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this absli.
	 *
	 * @return the group ID of this absli
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this absli.
	 *
	 * @param groupId the group ID of this absli
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this absli.
	 *
	 * @return the company ID of this absli
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this absli.
	 *
	 * @param companyId the company ID of this absli
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this absli.
	 *
	 * @return the user ID of this absli
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this absli.
	 *
	 * @param userId the user ID of this absli
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this absli.
	 *
	 * @return the user uuid of this absli
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this absli.
	 *
	 * @param userUuid the user uuid of this absli
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this absli.
	 *
	 * @return the user name of this absli
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this absli.
	 *
	 * @param userName the user name of this absli
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this absli.
	 *
	 * @return the create date of this absli
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this absli.
	 *
	 * @param createDate the create date of this absli
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this absli.
	 *
	 * @return the modified date of this absli
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this absli.
	 *
	 * @param modifiedDate the modified date of this absli
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the u ID of this absli.
	 *
	 * @return the u ID of this absli
	 */
	@AutoEscape
	public String getUId();

	/**
	 * Sets the u ID of this absli.
	 *
	 * @param uId the u ID of this absli
	 */
	public void setUId(String uId);

	/**
	 * Returns the product of this absli.
	 *
	 * @return the product of this absli
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this absli.
	 *
	 * @param product the product of this absli
	 */
	public void setProduct(String product);

	/**
	 * Returns the agent code of this absli.
	 *
	 * @return the agent code of this absli
	 */
	@AutoEscape
	public String getAgentCode();

	/**
	 * Sets the agent code of this absli.
	 *
	 * @param agentCode the agent code of this absli
	 */
	public void setAgentCode(String agentCode);

	/**
	 * Returns the source name of this absli.
	 *
	 * @return the source name of this absli
	 */
	@AutoEscape
	public String getSourceName();

	/**
	 * Sets the source name of this absli.
	 *
	 * @param sourceName the source name of this absli
	 */
	public void setSourceName(String sourceName);

	/**
	 * Returns the discount of this absli.
	 *
	 * @return the discount of this absli
	 */
	public boolean getDiscount();

	/**
	 * Returns <code>true</code> if this absli is discount.
	 *
	 * @return <code>true</code> if this absli is discount; <code>false</code> otherwise
	 */
	public boolean isDiscount();

	/**
	 * Sets whether this absli is discount.
	 *
	 * @param discount the discount of this absli
	 */
	public void setDiscount(boolean discount);

	/**
	 * Returns the created by of this absli.
	 *
	 * @return the created by of this absli
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this absli.
	 *
	 * @param createdBy the created by of this absli
	 */
	public void setCreatedBy(String createdBy);

	@Override
	public Absli cloneWithOriginalValues();

}